<?php
/**
 * SEO and response headers
 */

/**
 * "source" archives list every resource with their own query (taxonomy-source.php),
 * so the main query must not paginate: otherwise /page/2/, /page/3/... are duplicates
 * and Yoast prints rel="next" / og:url for them.
 */
add_action( 'pre_get_posts', 'it_source_archive_no_paging' );
function it_source_archive_no_paging( $query ) {
	if ( is_admin() || ! $query->is_main_query() || ! $query->is_tax( 'source' ) ) {
		return;
	}

	$query->set( 'posts_per_page', -1 );
	$query->set( 'no_found_rows', true );
}

/**
 * 301 old paginated "source" URLs (already crawled/indexed) to the archive itself
 */
add_action( 'template_redirect', 'it_source_archive_paged_redirect' );
function it_source_archive_paged_redirect() {
	// Query vars, not is_tax(): an empty term's /page/2/ is already a 404 here and has no queried object.
	$term_slug = get_query_var( 'source' );

	if ( ! $term_slug || get_query_var( 'paged' ) < 2 ) {
		return;
	}

	$term_link = get_term_link( $term_slug, 'source' );

	if ( ! is_wp_error( $term_link ) ) {
		wp_safe_redirect( $term_link, 301 );
		exit;
	}
}

/**
 * Basic security headers.
 * Only reaches responses generated by PHP: pages served from the page cache and static files
 * need the same headers at server level (nginx / .htaccess).
 */
add_action( 'send_headers', 'it_security_headers' );
function it_security_headers() {
	header( 'X-Frame-Options: SAMEORIGIN' );
	header( 'X-Content-Type-Options: nosniff' );
	header( 'Referrer-Policy: strict-origin-when-cross-origin' );

	if ( is_ssl() ) {
		header( 'Strict-Transport-Security: max-age=31536000' );
	}
}
